services:
  # The NestJS Backend
  - type: web
    name: rent-a-tool-backend
    runtime: node
    plan: free
    # Point to the backend folder
    rootDir: backend
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rent-a-tool-db
          property: connectionString

databases:
  # The PostgreSQL Database
  - name: rent-a-tool-db
    plan: free
    databaseName: rent_a_tool
    user: rent_a_tool
